Repository atlp-rwanda/e-comm-team-axel25-bn, pull requests merged in 2023-03, with the labels that each got.

#61 ft: add cart feature(view/add/delete)
  .hound.yml
  .prettierrc
  docs/cart.docs.yaml
  package.json
  src/controllers/Cart.controller.ts
  src/middleware/validation/product.schema.middleware.ts
  src/routes/cart.routes.ts
  src/services/Cart.service.ts
  src/services/Product.service.ts
  src/utils/calculateCartTotal.util.ts
  src/utils/index.ts
  src/utils/isValidUUID.util.ts
  test/cart.spec.ts
  test/product.spec.ts
  yarn.lock
Labels: enhancement

#91 bg: fix the linting errors after the introduction of hound-specific r…
  .github/pull_request_template.md
  .github/workflows/nodejs.yml
  README.md
  docker-compose.yml
  docs/auth.docs.yaml
  docs/cart.docs.yaml
  docs/product.docs.yaml
  docs/swagger.ts
  docs/user.docs.yaml
  jest.config.js
  src/app.ts
  src/controllers/Auth.controller.ts
  src/controllers/Checkout.controller.ts
  src/controllers/Product.controller.ts
  src/controllers/TwoFactorAuth.controller.ts
  src/controllers/User.controller.ts
  src/controllers/index.ts
  src/database/config/config.js
  src/database/migrations/20230227054250-create_users_table.js
  src/database/migrations/20230227054437-create_logged_in_users_table.js
  src/database/migrations/20230227054449-create_tokens_table.js
  src/database/migrations/20230227054500-create_products_table.js
  src/database/migrations/20230227054511-create_carts_table.js
  src/database/models/Cart.model.ts
  src/database/models/LoggedInUsers.model.ts
  src/database/models/Product.model.ts
  src/database/models/Token.model.ts
  src/database/models/User.model.ts
  src/database/models/index.ts
  src/database/seeders/20230227061419-seed_users.js
  src/database/seeders/20230227061426-seed_products.js
  src/interfaces/Cart.interface.ts
  src/interfaces/Product.interface.ts
  src/interfaces/User.interface.ts
  src/interfaces/index.ts
  src/middleware/auth/auth.middleware.ts
  src/middleware/auth/index.ts
  src/middleware/auth/passport.middleware.ts
  src/middleware/validation/index.ts
  src/middleware/validation/product.schema.middleware.ts
  src/middleware/validation/user.schema.middleware.ts
  src/middleware/validation/validation.middleware.ts
  src/routes/auth.routes.ts
  src/routes/cart.routes.ts
  src/routes/checkout.routes.ts
  src/routes/index.ts
  src/routes/passport.routes.ts
  src/routes/product.routes.ts
  src/routes/user.routes.ts
  src/server.ts
  src/services/Auth.service.ts
  src/services/Product.service.ts
  src/services/User.service.ts
  src/services/index.ts
  src/utils/index.ts
  src/utils/jwt.utils.ts
  src/utils/searchProducts.util.ts
  test/auth.spec.ts
  test/test.spec.ts
  test/user.spec.ts
Labels: Bug Fix, Ready

#81 ft:buyer view order status(add/get/delete)
  docs/order.docs.yaml
  src/controllers/Order.controller.ts
  src/controllers/index.ts
  src/database/migrations/20230305181417-create-order-tables.js
  src/database/models/Order.model.ts
  src/routes/index.ts
  src/routes/order.routes.ts
  src/services/Order.service.ts
  src/services/index.ts
  test/order.spec.ts
Labels: Bug Fix, Ready, Changes Requested

#82 feat: buyer can add product to wishlist(post,get and delete)
  docs/wishes.docs.yaml
  src/controllers/Order.controller.ts
  src/controllers/Wish.controller.ts
  src/controllers/index.ts
  src/database/migrations/20230305183456-create-wishlist-tables.js
  src/database/models/Wishes.model.ts
  src/interfaces/Wish.interface.ts
  src/interfaces/index.ts
  src/routes/index.ts
  src/routes/wishes.routes.ts
  src/services/Wishes.services.ts
  src/services/index.ts
  test/wishes.spec.ts
Labels: Bug Fix, Ready, BE, Changes Requested

#73 ft: #184361217 add update password feature for user in case they want to.
  docs/updatepassword.docs.yaml
  src/controllers/updatePassword.controller.ts
  src/database/migrations/20230227054250-create_users_table.js
  src/database/models/User.model.ts
  src/interfaces/User.interface.ts
  src/middleware/validation/user.schema.middleware.ts
  src/routes/auth.routes.ts
  test/updatePassword.spec.ts
Labels: Ready

#97 docs(swagger): add docs of password reset [#184361212]
  docs/resetPassword.docs.yaml
  src/controllers/Auth.controller.ts
  src/routes/auth.routes.ts
Labels: Ready

#78 ft:seller delete specific Item in collection
  .hound.yml
  docs/product.docs.yaml
  src/controllers/Product.controller.ts
  src/database/migrations/20230227054511-create_carts_table.js
  src/database/models/Cart.model.ts
  src/routes/product.routes.ts
  src/services/Product.service.ts
  test/auth.spec.ts
  test/product.spec.ts
  yarn.lock
Labels: Ready, Needs Rebase

#74 ft: #184361213 add Two Factor Authentication for Sellers
  docs/twofactorAuth.docs.yaml
  package.json
  src/controllers/TwoFactorAuth.controller.ts
  src/controllers/index.ts
  src/controllers/twoFactorAuth.controller.ts
  src/database/migrations/20230227054250-create_users_table.js
  src/database/models/User.model.ts
  src/interfaces/User.interface.ts
  src/routes/auth.routes.ts
  src/routes/cart.routes.ts
  src/routes/order.routes.ts
  src/routes/product.routes.ts
  src/routes/user.routes.ts
  src/services/mails/sendEmailToken.ts
  src/services/protectRoutes.service.ts
  test/product.spec.ts
  test/twoFactorAuthentication.spec.ts
  yarn.lock
Labels: Ready

#101 bg: fix cart bugs 🐛 🐞
  docs/cart.docs.yaml
  src/middleware/validation/product.schema.middleware.ts
  src/utils/calculateCartTotal.util.ts
Labels: Bug Fix, Ready

#86 ft: #184361206 Setup docker for backend application
  Dockerfile
  docker-compose.yml
Labels: Ready

#104 ft(product): add product view by ID [#184361222]
  docs/product.docs.yaml
  src/controllers/Product.controller.ts
  src/routes/product.routes.ts
  src/services/Product.service.ts
Labels: Ready

#100 fix(utilsJWT): fix token expiry for password reset [#184361212]
  .github/workflows/nodejs.yml
  docs/resetPassword.docs.yaml
  src/controllers/Auth.controller.ts
  src/controllers/User.controller.ts
  src/controllers/Wish.controller.ts
  src/middleware/auth/auth.middleware.ts
  src/routes/order.routes.ts
  src/routes/user.routes.ts
  src/routes/wishes.routes.ts
  src/services/User.service.ts
  src/services/protectRoutes.service.ts
  src/utils/jwt.utils.ts
  test/wishes.spec.ts
Labels: Bug Fix

#102 #184361232 Feat:admin can get all orders
  docs/order.docs.yaml
  src/controllers/Order.controller.ts
  src/database/migrations/20230305181417-create-order-tables.js
  src/database/models/Order.model.ts
  src/interfaces/Order.interface.ts
  src/interfaces/index.ts
  src/routes/order.routes.ts
  src/services/Order.service.ts
  test/order.spec.ts
Labels: Ready, Needs Rebase

#103 ft: #184361233 add payment using Stripe API
  jest.config.js
  src/controllers/Checkout.controller.ts
  src/database/config/config.js
  src/middleware/validation/checkout.schema.middleware.ts
  src/middleware/validation/index.ts
  src/routes/checkout.routes.ts
  test/cart.spec.ts
  test/twoFactorAuthentication.spec.ts
  test/updatePassword.spec.ts
  test/user.spec.ts
Labels: Ready

#70 #184361228 Feat:buyer should be able to update their cart
  docs/cart.docs.yaml
  src/controllers/Cart.controller.ts
  src/middleware/validation/product.schema.middleware.ts
  src/routes/cart.routes.ts
  src/services/Cart.service.ts
  test/cart.spec.ts
Labels: Ready

#64 #184361224 Feat: a seller should be able to update an product item from their collection
  docs/product.docs.yaml
  src/controllers/Product.controller.ts
  src/middleware/validation/product.schema.middleware.ts
  src/routes/product.routes.ts
  src/services/Product.service.ts
  test/product.spec.ts
Labels: Ready

#105 ft: #184361236 add daily check for expired products 🕐 🥫
  .husky/pre-commit
  docs/auth.docs.yaml
  docs/product.docs.yaml
  package.json
  src/controllers/twoFactorAuth.controller.ts
  src/database/migrations/20230227054500-create_products_table.js
  src/database/models/Product.model.ts
  src/database/seeders/20230227061426-seed_products.js
  src/interfaces/Product.interface.ts
  src/jobs/checkExpiredProducts.ts
  src/jobs/index.ts
  src/middleware/validation/product.schema.middleware.ts
  src/server.ts
  src/services/mail/index.ts
  src/services/mail/sendEmailToken.ts
  src/services/mail/sendExpiredProductNotice.ts
  test/cart.spec.ts
  test/twoFactorAuthentication.spec.ts
  yarn.lock
Labels: Ready

#112 ft:#184361237 check for expired passwords - every 90 days 🔐 🦅
  src/controllers/Auth.controller.ts
  src/controllers/User.controller.ts
  src/database/migrations/20230227054250-create_users_table.js
  src/database/models/User.model.ts
  src/interfaces/User.interface.ts
  src/jobs/checkExpiredPasswords.ts
  src/jobs/index.ts
  src/services/User.service.ts
  src/services/mail/sendExpiredPasswordNotices.ts
  src/utils/checkLoginIntegrity.util.ts
  src/utils/index.ts
  test/auth.spec.ts
  test/twoFactorAuthentication.spec.ts
Labels: Ready

#109 ft(notification): read all/a notification by ID [#184361235]
  docs/notification.docs.yaml
  src/routes/index.ts
  src/routes/notification.routes.ts
Labels: Ready, Needs Rebase

#111 #184361232 fx:change the way to get orders
  src/controllers/Order.controller.ts
  src/controllers/Product.controller.ts
  src/interfaces/Order.interface.ts
  src/services/Order.service.ts
  test/order.spec.ts
Labels: Ready

#108 add ft: admin should be able to disable any user account #184361215
  docs/disableAccount.docs.yaml
  src/controllers/AccountDisable.controller.ts
  src/controllers/index.ts
  src/database/migrations/20230312074609-modify_users_alter_column_status.js
  src/database/migrations/20230312080056-user_account_disabled_reasons.js
  src/database/models/DisabledAccount.model.ts
  src/interfaces/DisabledAccount.interface.ts
  src/interfaces/User.interface.ts
  src/interfaces/index.ts
  src/middleware/auth/auth.middleware.ts
  src/routes/accounts.routes.ts
  src/routes/index.ts
  src/services/protectRoutes.service.ts
  src/utils/checkLoginIntegrity.util.ts
  test/auth.spec.ts
  test/disableAccount.spec.ts
  test/user.spec.ts
Labels: Ready, Needs Peer Review

#106 #184361239 Feat: user chat
  .env.example
  docs/chat.docs.yaml
  jest.config.js
  package-lock.json
  package.json
  src/controllers/Chat.controller.ts
  src/database/migrations/20230311203450-create-chat-table.js
  src/database/models/Chat.model.ts
  src/interfaces/Chat.interface.ts
  src/interfaces/index.ts
  src/middleware/auth/socketAuth.middleware.ts
  src/routes/chat.routes.ts
  src/routes/index.ts
  src/server.ts
  test/chat.spec.ts
  yarn.lock
Labels: Ready, Needs Peer Review

#117 #184361226 ft-buyer-provide-review
  docs/productReview.docs.yaml
  package-lock.json
  src/controllers/Review.controller.ts
  src/controllers/index.ts
  src/database/migrations/20230315143718-review_product_table.js
  src/database/models/Reviews.model.ts
  src/interfaces/Review.interface.ts
  src/interfaces/index.ts
  src/routes/index.ts
  src/routes/review.routes.ts
  src/services/Review.service.ts
  src/services/index.ts
  test/productReview.spec.ts
  yarn.lock
Labels: Ready
