Repository atlp-rwanda/e-comm-team-axel25-bn, pull requests merged in 2023-02, with the labels that each got.

#3 Ft integrate cirlce ci
  .circleci/config.yml
Labels: enhancement

#4 ft: Unit testing setUp
  jest.config.js
  package.json
  pnpm-lock.yaml
  test/test.spec.ts
Labels: enhancement

#6 chore: add database connection
  .env.example
  package.json
  pnpm-lock.yaml
  src/controllers/_index.ts
  src/controllers/user.controller.ts
  src/db/config.ts
  src/db/schemas/_index.ts
  src/db/schemas/user.schema.ts
  src/interfaces/_index.ts
  src/interfaces/userInterfaces.ts
  src/middleware/validation/_index.ts
  src/middleware/validation/user.schema.middleware.ts
  src/middleware/validation/validation.middleware.ts
  src/routes/_index.ts
  src/routes/user.routes.ts
  src/server.ts
  src/services/_index.ts
  src/services/user.service.ts
Labels: enhancement

#12 fix: fix typerror in the user servise ts file
  src/controllers/user.controller.ts
  src/services/user.service.ts
Labels: documentation

#13 Chore hound ci
  .hound.yml
  hound.yml
Labels: enhancement

#15 fx:fixing tests
  test/test.spec.ts
Labels: documentation

#16 bg: update the build script, README.md, & .env.example
  .env.example
  README.md
  package.json
Labels: documentation

#21 Ft: registration
  .dockerignore
  Dockerfile
  docker-compose.yml
  package.json
  pnpm-lock.yaml
  src/controllers/user.controller.ts
  src/db/schemas/user.schema.ts
  src/interfaces/userInterfaces.ts
  src/middleware/validation/user.schema.middleware.ts
  src/utils/index.ts
  src/utils/jwt.utils.ts
Labels: enhancement

#22 Ft email verification
  .env.example
  package.json
  pnpm-lock.yaml
  src/controllers/user.controller.ts
  src/db/config.ts
  src/db/schemas/user.schema.ts
  src/interfaces/userInterfaces.ts
  src/middleware/validation/user.schema.middleware.ts
  src/routes/_index.ts
  src/routes/auth.routes.ts
  src/services/_index.ts
  src/services/auth.service.ts
  src/utils/_index.ts
  src/utils/index.ts
Labels: enhancement

#23 ft: add password reset via email
  pnpm-lock.yaml
  src/controllers/user.controller.ts
  src/db/schemas/user.schema.ts
  src/routes/auth.routes.ts
  src/services/auth.service.ts
  src/utils/jwt.utils.ts
Labels: documentation

#27 ft: setup swagger doc
  docs/schemas/user.schema.ts
  docs/swagger.ts
  docs/test.docs.ts
  docs/user.docs.ts
  package.json
  pnpm-lock.yaml
  src/controllers/auth.controller.ts
  src/db/config.ts
  src/routes/swagger.routes.ts
  src/server.ts
  tsconfig.json
  types.d.ts
Labels: documentation, enhancement

#57 #184361231 A user should be able to search a product
  docs/product.docs.ts
  docs/product.docs.yaml
  docs/swagger.ts
  docs/user.docs.yaml
  package.json
  src/controllers/Product.controller.ts
  src/database/seeders/20230227061419-seed_users.js
  src/database/seeders/20230227061426-seed_products.js
  src/services/Product.service.ts
  src/utils/index.ts
  src/utils/searchProducts.util.ts
  test/cart.spec.ts
  test/product.spec.ts
  test/user.spec.ts
  tsconfig.json
Labels: documentation, enhancement
